# Generated by Django 6.0.7 on 2026-08-13 18:27

from decimal import Decimal

from django.db import migrations, models


def reconstruct_investments(apps, schema_editor):
    Investment = apps.get_model('investments', 'Investment')
    Preference = apps.get_model('accounts', 'UserPreference')
    Rate = apps.get_model('banking', 'ExchangeRate')
    for operation in Investment.objects.select_related('asset').iterator():
        target = Preference.objects.filter(user_id=operation.user_id).values_list('base_currency', flat=True).first() or 'BRL'
        source = operation.asset.currency
        operation.fx_source_currency = source
        operation.fx_target_currency = target
        if source == target:
            operation.fx_rate = Decimal('1')
            operation.fx_snapshot_status = 'RECONSTRUCTED'
        else:
            rate = Rate.objects.filter(user_id=operation.user_id, from_currency=source, to_currency=target, effective_date__lte=operation.date).order_by('-effective_date', '-created_at').first()
            if rate:
                operation.fx_rate = rate.rate
                operation.fx_snapshot_status = 'RECONSTRUCTED'
            else:
                inverse = Rate.objects.filter(user_id=operation.user_id, from_currency=target, to_currency=source, effective_date__lte=operation.date).order_by('-effective_date', '-created_at').first()
                if inverse:
                    operation.fx_rate = (Decimal('1') / inverse.rate).quantize(Decimal('0.00000001'))
                    operation.fx_snapshot_status = 'RECONSTRUCTED'
        operation.save(update_fields=['fx_source_currency', 'fx_target_currency', 'fx_rate', 'fx_snapshot_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_asset_opening_balance_asset_opening_product'),
        ('accounts', '0001_userpreference'),
        ('banking', '0003_banktransfer_fx_rate_banktransfer_fx_snapshot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='fx_snapshot_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('RECONSTRUCTED', 'Reconstructed'), ('CAPTURED', 'Captured')], default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='fx_source_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='investment',
            name='fx_target_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.RunPython(reconstruct_investments, migrations.RunPython.noop),
    ]
