# Generated by Django 6.0.7 on 2026-08-15 14:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_investment_fx_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='opening_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Existing units before the first recorded operation.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='asset',
            name='opening_unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Unit price of the existing units.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
