# Generated by Django 6.0.8 on 2026-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_asset_opening_quantity_asset_opening_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='purpose',
            field=models.CharField(choices=[('INVESTMENT', 'Investment'), ('MONTHLY_CASH', 'Remunerated cash')], default='INVESTMENT', max_length=20),
        ),
    ]
