# Generated by Django 6.0.8 on 2026-10-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_investmentproduct_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
