# Generated by Django 6.0.7 on 2026-08-13 18:27

from decimal import Decimal
from django.db import migrations, models

def reconstruct_transfers(apps, schema_editor):
    Transfer = apps.get_model('banking', 'BankTransfer')
    for transfer in Transfer.objects.select_related('source_account', 'destination_account').iterator():
        if transfer.source_account.currency == transfer.destination_account.currency:
            continue
        transfer.fx_source_currency = transfer.source_account.currency
        transfer.fx_target_currency = transfer.destination_account.currency
        transfer.fx_rate = (Decimal(transfer.destination_amount) / Decimal(transfer.source_amount)).quantize(Decimal('0.00000001'))
        transfer.fx_snapshot_status = 'RECONSTRUCTED'
        transfer.save(update_fields=['fx_source_currency', 'fx_target_currency', 'fx_rate', 'fx_snapshot_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_loyaltyentry_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='fx_snapshot_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('RECONSTRUCTED', 'Reconstructed'), ('CAPTURED', 'Captured')], default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='fx_source_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='fx_target_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.RunPython(reconstruct_transfers, migrations.RunPython.noop),
    ]
