# Generated by Django 6.0.8 on 2026-09-20 15:59

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_creditcard_card_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='planning_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money to keep outside monthly planning, in this account currency.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_amount__gte', 0)), name='banking_account_reserved_amount_gte_zero'),
        ),
    ]
