# Generated by Django 6.0.8 on 2026-09-21 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bankaccount_planning_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='color',
            field=models.CharField(blank=True, default='#B88D57', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a color in #RRGGBB format.')]),
        ),
    ]
