# Generated by Django 6.0.8 on 2026-10-03 16:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_iof_transactions(apps, schema_editor):
    Redemption = apps.get_model('banking', 'RewardRedemption')
    Transaction = apps.get_model('transactions', 'Transaction')
    Category = apps.get_model('categories', 'Category')
    alias = schema_editor.connection.alias
    for redemption in Redemption.objects.using(alias).filter(iof_amount__gt=0).iterator():
        index = 1
        while True:
            name = 'IOF' if index == 1 else f'IOF ({index})'
            category, _ = Category.objects.using(alias).get_or_create(
                user_id=redemption.user_id, name=name,
                defaults={'transaction_type': 'EXPENSE'},
            )
            if category.transaction_type != 'INCOME':
                break
            index += 1
        Transaction.objects.using(alias).get_or_create(
            reward_redemption_id=redemption.pk,
            defaults={
                'user_id': redemption.user_id, 'title': 'IOF on reward redemption',
                'amount': redemption.iof_amount, 'transaction_type': 'EXPENSE',
                'category_id': category.pk,
                'payment_channel': 'CREDIT_CARD' if redemption.iof_credit_card_id else 'ACCOUNT',
                'bank_account_id': redemption.iof_account_id,
                'credit_card_id': redemption.iof_credit_card_id,
                'date': redemption.date, 'notes': redemption.notes,
            },
        )


def remove_iof_transactions(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    Transaction.objects.using(schema_editor.connection.alias).filter(
        reward_redemption__isnull=False,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_bank_color'),
        ('categories', '0002_category_transaction_type'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reward_redemption',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iof_transaction', to='banking.rewardredemption'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.RunPython(backfill_iof_transactions, remove_iof_transactions),
    ]
