# Generated by Django 6.0.7 on 2026-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fixed_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
