# Generated by Django 6.0.7 on 2026-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_fixed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billing_override',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Current bill'), (1, 'Next bill')], default=None, null=True),
        ),
    ]
