# Generated by Django 6.0.7 on 2026-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], help_text='Optional. Unclassified categories can be used for income and expenses.', max_length=10, null=True),
        ),
    ]
